### ISSUE TITLE
Bug / Fails to run 

### ISSUE THREAD

**Issue by bayoumymac** [launchdarkly/find-code-references-in-pull-request#87]
Hey y'all,

I ran into the following bug upon using this action

I tested the following versions:
- v1.1.0
- v1.0.0

```
Error: error parsing GitHub event payload at "/github/workflow/event.json": json: cannot unmarshal string into Go struct field Repository.repository.organization of type github.Organization
```

Any idea how to fix?

**Comment by bayoumymac** [comment]
@jazanne you are right, i was using `push` instead of `pull_request`

thank you for the quick response

**Comment by jazanne** [comment]
Glad to hear that worked for you!
